// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies ApS";
    extern const char* const UnityCopyright = "(c) 2022 Unity Technologies ApS. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/build/output/unity/unity";

    extern const char* const UnityVersion = "2022.1.24f1";
    extern const char* const UnityVersionDigits = "2022.1.24";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2022;
    extern const UInt32 UnityVersionMajor = 1;
    extern const UInt32 UnityVersionMinor = 24;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2022.1.24f1_709dddfb713f";
    extern const char* const UnityVersionUnderHash_Verbose = "2022.1.24f1_709dddfb713f";
    extern const char* const UnityVersionUnderHash_WithParens = "2022.1.24f1 (709dddfb713f)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 7380445;

    extern const UInt64 UnityVersionDate = 1669969244;
    extern const char* const UnityVersionBranch = "2022.1/staging";
    extern const char* const UnityVersionDisplay = "2022.1.24f1";
    extern const char* const UnityVersionDisplay_Verbose = "2022.1.24f1.git.7380445";
    extern const char* const UnityVersionRevision = "709dddfb713f";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2022.1.24f1 (709dddfb713f)";
    extern const wchar_t* const L_UnityVersion = L"2022.1.24f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies ApS"
    #define UNITY_COPYRIGHT "(c) 2022 Unity Technologies ApS. All rights reserved."
    #define UNITY_VERSION_VER 2022
    #define UNITY_VERSION_MAJ 1
    #define UNITY_VERSION_MIN 24
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2022.1.24f1_709dddfb713f"
    #define UNITY_VERSION_PARENS_HASH "2022.1.24f1 (709dddfb713f)"
    #define UNITY_VERSION_BLD 7380445
    #define UNITY_VERSION_WIN "2022.1.24.7380445"

#endif // !RC_INVOKED
